'use client';
import { useState } from 'react';
import axios from 'axios';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { FileDown, CheckCircle, XCircle } from 'lucide-react'; // FileDown icon add kiya PDF ke liye
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function QuotationManager() {
  const queryClient = useQueryClient();
  const { register, handleSubmit, reset } = useForm();

  // Fetch Vendors for Dropdown
  const { data: vendors = [] } = useQuery({
    queryKey: ['vendors'],
    queryFn: async () => {
      const res = await axios.get('http://localhost:5000/api/vendors');
      return res.data.data;
    }
  });

  // Fetch Quotations
  const { data: quotations = [], isLoading } = useQuery({
    queryKey: ['quotations'],
    queryFn: async () => {
      const res = await axios.get('http://localhost:5000/api/quotations');
      return res.data.data;
    }
  });

  // Create Quotation Mutation
  const createMutation = useMutation({
    mutationFn: async (data) => await axios.post('http://localhost:5000/api/quotations', data),
    onSuccess: () => {
      queryClient.invalidateQueries(['quotations']);
      reset();
      alert('Quotation Assigned Successfully!');
    }
  });

  // Update Status Mutation
  const statusMutation = useMutation({
    mutationFn: async ({ id, status }) => await axios.patch(`http://localhost:5000/api/quotations/${id}/status`, { status }),
    onSuccess: () => queryClient.invalidateQueries(['quotations'])
  });

  const onSubmit = (data) => createMutation.mutate(data);

  // 📄 PDF GENERATOR FUNCTION
  const exportToPDF = (quote) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185); // Blue Color
    doc.text('TEYZIX CORE', 14, 20);
    
    doc.setFontSize(16);
    doc.setTextColor(44, 62, 80); // Dark Gray
    doc.text('Official Quotation Document', 14, 30);
    
    // Quotation Details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Quotation Title: ${quote.quotationTitle}`, 14, 45);
    doc.text(`Date Submitted: ${new Date(quote.createdAt).toLocaleDateString()}`, 14, 52);
    doc.text(`Status: ${quote.status}`, 14, 59);
    doc.text(`Total Amount: $${quote.quotationAmount}`, 14, 66);

    // FIX: Yahan doc.autoTable ki jagah autoTable(doc, ...) use kiya hai
    autoTable(doc, {
      startY: 75,
      head: [['Vendor Name', 'Company Name', 'Email']],
      body: [
        [quote.vendor?.vendorName || 'N/A', quote.vendor?.companyName || 'N/A', quote.vendor?.email || 'N/A'],
      ],
      headStyles: { fillColor: [41, 128, 185] }
    });

    // Description
    const finalY = doc.lastAutoTable?.finalY || 100; // FIX: Fallback value if undefined
    doc.setFontSize(12);
    doc.text('Description / Requirements:', 14, finalY + 15);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const splitDesc = doc.splitTextToSize(quote.description, 180);
    doc.text(splitDesc, 14, finalY + 22);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Teyzix Vendor Management System', 14, 280);

    // Save File
    doc.save(`Quotation_${quote.quotationTitle.replace(/\s+/g, '_')}.pdf`);
  };
  return (
    <div className="max-w-7xl mx-auto space-y-8">
      <h1 className="text-3xl font-bold text-gray-800 dark:text-white border-b dark:border-gray-700 pb-2 transition-colors">
        Quotation Management
      </h1>

      {/* Add Quotation Form */}
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 transition-colors">
        <h2 className="text-xl font-bold mb-4 text-gray-700 dark:text-gray-300">Request New Quotation</h2>
        <form onSubmit={handleSubmit(onSubmit)} className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <input {...register('quotationTitle', { required: true })} placeholder="Quotation Title (e.g. 10 Laptops)" className="border dark:border-gray-600 bg-transparent dark:text-white p-2 rounded focus:ring-2 focus:ring-blue-400 outline-none" />
          
          <select {...register('vendor', { required: true })} className="border dark:border-gray-600 bg-transparent dark:text-white p-2 rounded focus:ring-2 focus:ring-blue-400 outline-none">
            <option value="" className="dark:bg-gray-800">-- Select Vendor to Assign --</option>
            {vendors.map(v => (
              <option key={v._id} value={v._id} className="dark:bg-gray-800">{v.vendorName} ({v.companyName})</option>
            ))}
          </select>

          <input {...register('quotationAmount', { required: true })} type="number" placeholder="Proposed Amount ($)" className="border dark:border-gray-600 bg-transparent dark:text-white p-2 rounded focus:ring-2 focus:ring-blue-400 outline-none" />
          <input {...register('description', { required: true })} placeholder="Details / Requirements" className="border dark:border-gray-600 bg-transparent dark:text-white p-2 rounded focus:ring-2 focus:ring-blue-400 outline-none" />
          
          <button type="submit" disabled={createMutation.isPending} className="md:col-span-2 bg-blue-600 text-white font-bold py-2 rounded hover:bg-blue-700 disabled:bg-blue-400 transition">
            {createMutation.isPending ? 'Assigning...' : 'Assign Quotation'}
          </button>
        </form>
      </div>

      {/* Quotation List */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border dark:border-gray-700 overflow-hidden transition-colors">
        {isLoading ? <p className="p-8 text-center text-gray-500 dark:text-gray-400 animate-pulse">Loading Quotations...</p> : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse min-w-max">
              <thead className="bg-gray-50 dark:bg-gray-900 text-gray-600 dark:text-gray-400 uppercase text-xs border-b dark:border-gray-700">
                <tr>
                  <th className="p-4">Quotation Details</th>
                  <th className="p-4">Assigned Vendor</th>
                  <th className="p-4">Amount</th>
                  <th className="p-4">Status</th>
                  <th className="p-4 text-center">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y dark:divide-gray-700">
                {quotations.map(q => (
                  <tr key={q._id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition">
                    <td className="p-4">
                      <p className="font-bold text-gray-800 dark:text-white">{q.quotationTitle}</p>
                      <p className="text-xs text-gray-500 dark:text-gray-400 line-clamp-1 max-w-[200px]">{q.description}</p>
                    </td>
                    <td className="p-4 font-semibold text-blue-600 dark:text-blue-400">{q.vendor?.vendorName}</td>
                    <td className="p-4 font-black text-green-600 dark:text-green-400">${q.quotationAmount}</td>
                    <td className="p-4">
                      <span className={`px-3 py-1 text-[10px] font-black uppercase rounded-full ${
                        q.status === 'Approved' ? 'bg-green-100 text-green-700' : 
                        q.status === 'Rejected' ? 'bg-red-100 text-red-700' : 'bg-yellow-100 text-yellow-700'
                      }`}>
                        {q.status}
                      </span>
                    </td>
                    <td className="p-4 flex items-center justify-center gap-2">
                      {q.status === 'Pending' && (
                        <>
                          <button onClick={() => statusMutation.mutate({ id: q._id, status: 'Approved' })} className="text-green-500 hover:text-green-700 bg-green-50 dark:bg-gray-700 p-2 rounded-full transition" title="Approve">
                            <CheckCircle size={18} />
                          </button>
                          <button onClick={() => statusMutation.mutate({ id: q._id, status: 'Rejected' })} className="text-red-500 hover:text-red-700 bg-red-50 dark:bg-gray-700 p-2 rounded-full transition" title="Reject">
                            <XCircle size={18} />
                          </button>
                        </>
                      )}
                      
                      {/* 📄 EXPORT TO PDF BUTTON */}
                      <button 
                        onClick={() => exportToPDF(q)} 
                        className="text-blue-500 hover:text-blue-700 bg-blue-50 dark:bg-gray-700 p-2 rounded-full transition ml-2 border border-blue-200 dark:border-gray-600"
                        title="Download PDF"
                      >
                        <FileDown size={18} />
                      </button>
                    </td>
                  </tr>
                ))}
                {quotations.length === 0 && (
                  <tr>
                    <td colSpan="5" className="p-8 text-center text-gray-500 italic">No quotations found.</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}